### ISSUE TITLE
NSF on Multiple visium samples 

### ISSUE THREAD

**Issue by yeswzc** [willtownes/nsf-paper#9]
Hi, is there are way to perform NSF using merged visium data from multiple samples?

Thank you!

**Comment by willtownes** [comment]
There's probably a way to do it, but the current implementation was designed only for a single slice at a time and I haven't had time to make any updates. @luisdiaz1997 is this something you are working on?

**Comment by tmchartrand** [comment]
I'm not sure how relevant this is, but I've been running successfully using 3D coordinates across multiple sections of the same dataset. I would assume that even if your sections are completely different samples, you could artificially add a third dimension to space them sufficiently far apart as to not interact spatially. You'll need to skip the spatial normalization so it doesn't pull them back together, and perhaps some other minor tweaks to the preprocessing that I've forgotten. Normalizing by mean counts will likely also be important since detection efficiency tends to vary across samples (sz="mean").

**Comment by yeswzc** [comment]
> I'm not sure how relevant this is, but I've been running successfully using 3D coordinates across multiple sections of the same dataset. I would assume that even if your sections are completely different samples, you could artificially add a third dimension to space them sufficiently far apart as to not interact spatially. You'll need to skip the spatial normalization so it doesn't pull them back together, and perhaps some other minor tweaks to the preprocessing that I've forgotten. Normalizing by mean counts will likely also be important since detection efficiency tends to vary across samples (sz="mean").

Thank you! I was thinking about this kind of method too because I saw somewhere else used similar strategy. I haven't trid yet.
